import { Info } from 'lucide-react';
import { useState } from 'react';

export function StatusInfoIcon() {
  const [showTooltip, setShowTooltip] = useState(false);

  return (
    <div className="relative inline-block">
      <button
        onMouseEnter={() => setShowTooltip(true)}
        onMouseLeave={() => setShowTooltip(false)}
        onClick={() => setShowTooltip(!showTooltip)}
        className="p-1 text-gray-400 hover:text-gray-600 rounded-full transition-colors"
        title="Summary status information"
      >
        <Info className="w-4 h-4" />
      </button>

      {showTooltip && (
        <div className="absolute left-1/2 -translate-x-1/2 top-full mt-2 w-64 bg-gray-900 text-white text-sm rounded-lg shadow-lg p-3 z-[9999]">
          <div className="space-y-2">
            <div>
              <span className="font-semibold text-yellow-400">Processing</span> – Summary is being generated by the system
            </div>
            <div>
              <span className="font-semibold text-orange-400">Unverified</span> – Summary is generated but awaiting your confirmation
            </div>
            <div>
              <span className="font-semibold text-green-400">Verified</span> – Summary is confirmed and shared to MTBs
            </div>
            <div>
              <span className="font-semibold text-red-400">Failed</span> – Summary generation encountered an error
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
